"""add new row

Revision ID: 8212ba43ce0d
Revises: 949fd5d1449b
Create Date: 2023-07-25 22:16:29.343919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8212ba43ce0d'
down_revision = '949fd5d1449b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_private_key', sa.LargeBinary(length=32), server_default='', nullable=False))
        batch_op.add_column(sa.Column('encrypted_public_key', sa.LargeBinary(length=32), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('encrypted_public_key')
        batch_op.drop_column('encrypted_private_key')

    # ### end Alembic commands ###
