"""add new row

Revision ID: 8e9108f8acf3
Revises: 75a6e5995395
Create Date: 2023-07-25 22:11:24.595343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9108f8acf3'
down_revision = '75a6e5995395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_symmetric_key', sa.LargeBinary(length=32), nullable=False))
        batch_op.add_column(sa.Column('encrypted_private_key', sa.LargeBinary(length=32), nullable=False))
        batch_op.add_column(sa.Column('encrypted_public_key', sa.LargeBinary(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('encrypted_public_key')
        batch_op.drop_column('encrypted_private_key')
        batch_op.drop_column('encrypted_symmetric_key')

    # ### end Alembic commands ###
