"""add new models in file

Revision ID: a6642b334ccd
Revises: ebd34bf523de
Create Date: 2023-07-27 15:45:30.131960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6642b334ccd'
down_revision = 'ebd34bf523de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_tokens', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('expire_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_downloads', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('max_downloads')
        batch_op.drop_column('expire_time')
        batch_op.drop_column('download_tokens')

    # ### end Alembic commands ###
